# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
    {
        :name => "scylla1",
        :eth1 => "192.168.205.10",
        :mem => "1028",
        :cpu => "1"
    },
    {
        :name => "scylla2",
        :eth1 => "192.168.205.11",
        :mem => "1028",
        :cpu => "1"
    },
    {
        :name => "scylla3",
        :eth1 => "192.168.205.12",
        :mem => "1028",
        :cpu => "1"
    }
]

Vagrant.configure(2) do |config|

  config.vm.box = "puppetlabs/centos-7.2-64-nocm"

  # Turn off shared folders
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

  boxes.each do |opts|
    config.vm.define opts[:name] do |config|

      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip:opts[:eth1]

      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end
  
      config.vm.provision "ansible", run: "always" do |ansible|
        ansible.playbook = "ansiblePlaybook.yml"
      end

    end

  end
  
end